#------------------#
# General Settings #
#------------------#
# updatecheck, check for new version and give a message to the server console #
updatecheck: false
# autoupdate, is not implemented now and should always false #
autoupdate: false
# 
plugin_name: "Realms"
plugin_ver : "0.2.0"
realmCounter: 0
settlementCounter: 0
buildingCounter: 0

#---------------------------------------------
#     Settlement /superregions
# the SettlementTypes are predefined
# every SettlementTypes are unique in this list
#
superSettleTypes:
    SETTLE_HAMLET: "Mine"
    SETTLE_CASTLE: "Burg"
    SETTLE_HAMLET: "Siedlung"
    SETTLE_TOWN: "Dorf"
    SETTLE_CITY: "Stadt"
    SETTLE_METRO: "Metropole"
#---------------------------------------------
#   regions / BuildingType
# the BuildungTypes are predefined
# the regions are unique in this list
#
regionBuildingTypes:
    haus_einfach: "BUILDING_HOME"
    haus_gross: "BUILDING_HOME"
    haupthaus: "BUILDING_HALL"
    taverne: "BUILDING_ENTERTAIN"
    markt: "BUILDING_WAREHOUSE"
    kornfeld: "BUILDING_PROD"
    holzfaeller: "BUILDING_PROD"

