#------------------#
# General Settings #
#------------------#
# updatecheck, check for new version and give a message to the server console #
updatecheck: true
#
# autoupdate, is not implemented now and should always false #
autoupdate: false
#
# new option for protokoll files 
# logList, if true all production and orders and happiness on every production cycle will be stored
loglist: false 

plugin_name: "Realms"
plugin_ver : "0.9.0"
realmCounter: 0
settlementCounter: 0
buildingCounter: 0

spawnAnimal: false;

#---------------------------------------------
# Settlement /superregions for older versions of your superregions to get into realms
# the SettlementTypes are predefined
# every SettlementTypes are unique in this list
#
superSettleTypes:
    HAMLET: "Mine"
    CASTLE: "Burg"
    HAMLET: "Siedlung"
    TOWN: "Dorf"
    CITY: "Stadt"
    METROPOLIS: "Metropole"
#---------------------------------------------
# regions / BuildingType for older versions of your regions to get into realms
# the BuildungTypes are predefined
# the regions are unique in this list
#
regionBuildingTypes:
    haus_einfach: "HOME"
    haus_gross: "HOUSE"
    haupthaus: "HALL"
    taverne: "ENTERTAIN"
    markt: "WAREHOUSE"
    kornfeld: "WHEAT"
    holzfaeller: "WOODCUTTER"

