name: Realms
database: false
main: net.krglok.realms.Realms
version: 0.9.3
description: Allows you to create settlements based on herostronghold regions. Expand the settlement with buildings. Trade with other settlements. Build Kingdoms.
author: krglok
startup: postworld
website: http://dev.bukkit.org/bukkit-plugins/realms/
depend: [Vault,HeroStronghold,Citizens]
commands:
    realms:
        description: Basic command only show version and commandlist. The plugin has an integrated help system.
        usage: "/realms only for ops to control model and setup
 /owner player and ops for managing owners 
 /kingdom player command for realm management
 /feudal player command for control lehen
 /settle player command for settlement management
 /colonist player command for control colonists
 /regiment player command for control regiments
 "
    feudal: 
        description: player and ops command for managing lehen
        usage: /feudal HELP for more information
    owner: 
        description: only for ops for managing owners
        usage: /owner HELP for more information  
    kingdom:
        description: player command for kingdom management 
        usage: /realm HELP for more information   
    settle:
        description: player command for settlement management
        usage: /settle HELP for more information  
    colonist:
        description: player command for colonist managment
        usage: /colonist HELP for more information
    regiment:
        description: player command for regiment managment
        usage: /regiment HELP for more information
permissions:
    realms.admin:
        description: Gives access to admin commands
        default: op
    realms.user:
        description: Allows you to use public commands
        default: true
        